/**
 * Swagger Petstore hjkfg
 * This is a sampledjkkkkkkkkjjjjjhjjjjjjjjjjjjjjjjjjjjjjj Petstore server.  You can find  out more about Swagger at  [http://swagger.io](http://swagger.io) or on  [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.model.User
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object DefaultApi {

  /**
   * wwwwwww
   * 
   * Expected answers:
   *   code 0 :  (successful operation)
   * 
   * @param body List of user object
   */
  def createUsersWithListInput(body: Seq[User]): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://dev-virtserver.swaggerhub.com/DeltaDental/test-client-sdk/1.0.0", "/user/createWithList", "application/json")
      .withBody(body)
      .withDefaultSuccessResponse[Unit]
      

}

