openapi: 3.0.0
info:
  version: '1'
  title: 'test'
  description: 'my decription'
paths: {}
# Added by API Auto Mocking Plugin
servers:
  - description: Change on Repo
    url: https://dev-virtserver.swaggerhub.com/STEAM_3061/TestPULL0as3/1
